trigger:
  branches:
    include:
      - main

variables:
  # Variables de entorno
  ACR_NAME: 'rc002agrupo9sum3' # Colocar el nombre de tu ACR
  IMAGE_NAME: '002agrupo9-sum3-imagen' # Colocar el Nombre de Imagen
  SERVICE_CONNECTION_NAME: 'sc-002agrupo9-sum3-container' # Colocar nombre del Service Connection ubicado en Docker Registry-- Azure Container Registry

jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          containerRegistry: '$(SERVICE_CONNECTION_NAME)'
          repository: '$(IMAGE_NAME)'
          dockerfile: '**/Dockerfile'
          tags: |
            latest
        displayName: 'Build and Push Docker Image'
